/** @format */

import type { Metadata } from 'next';
import { Instrument_Serif, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Instrument_Serif({
	variable: '--font-geist-sans',
	subsets: ['latin'],
	weight: ['400'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
